include(GNUInstallDirs)

macro(define_standard_variables)
    file(STRINGS ${CMAKE_HOME_DIRECTORY}/NAME PROJECT_NAME)
    file(STRINGS ${CMAKE_HOME_DIRECTORY}/VERSION PROJECT_VERSION)
    file(STRINGS ${CMAKE_HOME_DIRECTORY}/WELCOME WELCOME)
    file(STRINGS ${CMAKE_HOME_DIRECTORY}/GITHUB_URL GITHUB_URL)
endmacro(define_standard_variables)

function(display_welcome)
    foreach(MSG ${WELCOME})
        string(REPLACE "{NAME}" ${PROJECT_NAME} MSG ${MSG})
        string(REPLACE "{VERSION}" ${PROJECT_VERSION} MSG ${MSG})
        string(REPLACE "{GITHUB_URL}" ${GITHUB_URL} MSG ${MSG})
        message(${MSG})
    endforeach()
endfunction(display_welcome)
